[workspace]
allow_dirty = false
changelog_update = false
dependencies_update = false
git_release_enable = false
git_tag_enable = false
pr_branch_prefix = "release-plz-"
publish = false
release_always = false
semver_check = true

[changelog]
commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Changed" },
  { message = "^revert", group = "Reverted" },
  { message = "^.*", skip = true },
]
protect_breaking_commits = true

[[package]]
name = "boxferry-model"
version_group = "boxferry"

[[package]]
name = "boxferry-engine"
version_group = "boxferry"

[[package]]
name = "boxferry-compose"
version_group = "boxferry"

[[package]]
name = "boxferry-podman"
version_group = "boxferry"

[[package]]
name = "boxferry-quadlet"
version_group = "boxferry"

[[package]]
name = "boxferry"
changelog_include = [
  "boxferry-compose",
  "boxferry-engine",
  "boxferry-model",
  "boxferry-podman",
  "boxferry-quadlet",
]
changelog_path = "CHANGELOG.md"
changelog_update = true
version_group = "boxferry"
