[package]
name = "boxferry-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Format-independent application model for BoxFerry"
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = true

[lints]
workspace = true
